// <auto-generated />
using System;
using IdentityService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IdentityService.Migrations {
    [DbContext (typeof (AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation ("ProductVersion", "3.1.3")
                .HasAnnotation ("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity ("IdentityServer.User", b => {
                b.Property<Guid> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("uuid");

                b.Property<string> ("Email")
                    .HasColumnType ("text");

                b.Property<string> ("Password")
                    .HasColumnType ("text");

                b.Property<string> ("Phone")
                    .HasColumnType ("text");

                b.Property<string> ("Salt")
                    .HasColumnType ("text");

                b.HasKey ("Id");

                b.ToTable ("Users");
            });
#pragma warning restore 612, 618
        }
    }
}