version: "3.0"
services:

    webapi_service:
        image: phrygia_webapi_service
        build:
          context: .
          dockerfile: ./AppServices/WebAPIService/Dockerfile        
        container_name: webapi_service
        ports:
          - "5002:80"
          - "5003:443"
        environment: 
          API_DB_HOST: "172.17.0.1"
          API_DB_PORT: "5432"
          API_DB_USER: "postgres"
          API_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          PIS_HOST: "172.17.0.1"
          PIS_PORT: "5000"
          RMQ_USER: "rabbitmq"
          RMQ_PASSWORD: "IlJU7f71Vh7rM1yv"
          RMQ_HOST: "172.17.0.1"
          RMQ_PORT: "5672"
          ASPNETCORE_ENVIRONMENT: "Development"          
        depends_on:    
          -  identity_service  
          -  rabbitmq  
          
          
    identity_service:
        image: phrygia_identity_service
        build:
          context: ./AppServices/IdentityService
          dockerfile: Dockerfile        
        container_name: identity_service
        ports:
          - "5000:80"
          - "5001:443"
        environment: 
          PIS_DB_HOST: "172.17.0.1"
          PIS_DB_PORT: "5432"
          PIS_DB_USER: "postgres"
          PIS_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:
          -  db     


    db:
        image: postgres:12.2-alpine
        volumes: 
          - pg_data:/var/lib/postgresql/data        
        ports: 
          - "5432:5432"
        container_name: pg
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PASSWORD: "IlJU7f71Vh7rM1yv"
            POSTGRES_USER: "postgres"

    
    rabbitmq:
        image: rabbitmq
        build:
          context: ./ThirdPartyImages
          dockerfile: RabbitMQ
        container_name: rabbitmq
        environment: 
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "IlJU7f71Vh7rM1yv"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:15672"]
          interval: 30s
          timeout: 10s
          retries: 5
        volumes:
            - rmq_etc:/etc/rabbitmq/
            - rmq_data:/var/lib/rabbitmq/
            - rmq_logs:/var/log/rabbitmq/
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"

    notification_worker:
        image: phrygia_notification_worker
        build:
          context: .
          dockerfile: ./AppServices/WorkerServices/NotificationWorkerService/Dockerfile        
        container_name: notification_worker
        restart: on-failure
        environment: 
          RMQ_USER: "rabbitmq"
          RMQ_PASSWORD: "IlJU7f71Vh7rM1yv"
          RMQ_HOST: "172.17.0.1"
          RMQ_PORT: "5672"
          DOTNET_ENVIRONMENT: "Development"
        depends_on:    
          -  rabbitmq  

volumes: 
  pg_data:
  rmq_etc:
  rmq_data:
  rmq_logs:

