version: "3.0"
services:

    webapi_service:
        image: phrygia_webapi_service
        build:
          context: .
          dockerfile: ./AppServices/WebAPIService/Dockerfile        
        container_name: webapi_service
        ports:
          - "5002:5002"
          - "5003:5003"
        environment: 
          API_DB_HOST: "172.17.0.1"
          API_DB_PORT: "5432"
          API_DB_USER: "postgres"
          API_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          PIS_HOST: "172.17.0.1"
          PIS_PORT: "5000"
          RMQ_USER: "rabbitmq"
          RMQ_PASSWORD: "IlJU7f71Vh7rM1yv"
          RMQ_HOST: "172.17.0.1"
          RMQ_PORT: "5672"
          ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:    
          -  identity_service  
          -  rabbitmq  
        #networks:
         # services-network:
          #  aliases:
           # - webapi_service
  
    identity_service:
        image: phrygia_identity_service
        build:
          context: ./AppServices/IdentityService
          dockerfile: Dockerfile        
        container_name: identity_service
        ports:
          - "5000:5000"
          - "5001:5001"
        environment: 
          PIS_DB_HOST: "172.17.0.1"
          PIS_DB_PORT: "5432"
          PIS_DB_USER: "postgres"
          PIS_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:
          -  db        
        #networks:
          #services-network:
           # aliases:
         #   - identity_service      
    db:
        image: postgres:12.2-alpine
        volumes: 
          - pg_data:/var/lib/postgresql/data        
        ports: 
          - "5432:5432"
        container_name: pg
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PASSWORD: "IlJU7f71Vh7rM1yv"
            POSTGRES_USER: "postgres"
        #networks:
         # services-network:
          #  aliases:
           #   - db
    
    rabbitmq:
        image: rabbitmq:3.8.3-management-alpine
        container_name: rabbitmq
        environment: 
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "IlJU7f71Vh7rM1yv"
        volumes:
            - rmq_etc:/etc/rabbitmq/
            - rmq_data:/var/lib/rabbitmq/
            - rmq_logs:/var/log/rabbitmq/
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"

volumes: 
  pg_data:
  rmq_etc:
  rmq_data:
  rmq_logs:

#networks:
 # services-network:    
  #  driver: bridge