version: "3"
services:

    webapi_service:
        build:
          context: .
          dockerfile: ./AppServices/WebAPIService/Dockerfile        
        container_name: webapi_service
        restart: unless-stopped
        expose:
          - 5002
        environment: 
          API_DB_HOST: "db"
          API_DB_PORT: "5432"
          API_DB_USER: "postgres"
          API_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          PIS_HOST: "identity_service"
          PIS_PORT: "5000"
          RMQ_USER: "rabbitmq"
          RMQ_PASSWORD: "IlJU7f71Vh7rM1yv"
          RMQ_HOST: "rabbitmq"
          RMQ_PORT: "5672"
          ASPNETCORE_ENVIRONMENT: "Development"          
          SeqURL: "http://seq:5341"
        depends_on:    
          -  identity_service  
          -  rabbitmq  
          -  seq
          
          
    identity_service:
        build:
          context: .
          dockerfile: ./AppServices/IdentityService/Dockerfile        
        container_name: identity_service
        restart: unless-stopped
        expose:
          - 5000
        environment: 
          PIS_DB_HOST: "db"
          PIS_DB_PORT: "5432"
          PIS_DB_USER: "postgres"
          PIS_DB_PASSWORD: "IlJU7f71Vh7rM1yv"
          ASPNETCORE_ENVIRONMENT: "Development"
          Serilog__WriteTo__2__Args__serverUrl: "http://seq:5341"
        depends_on:
          -  db     


    db:
        image: postgres:11.7-alpine
        volumes: 
          - pg_data:/var/lib/postgresql/data        
        ports: 
          - 5432:5432
        container_name: pg
        restart: unless-stopped
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PASSWORD: "IlJU7f71Vh7rM1yv"
            POSTGRES_USER: "postgres"

    
    rabbitmq:
        build:
          context: ./ThirdPartyImages
          dockerfile: RabbitMQ
        container_name: rabbitmq
        restart: unless-stopped
        environment: 
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "IlJU7f71Vh7rM1yv"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:15672"]
          interval: 30s
          timeout: 10s
          retries: 5
        volumes:
            - rmq_etc:/etc/rabbitmq/
            - rmq_data:/var/lib/rabbitmq/
            - rmq_logs:/var/log/rabbitmq/
        expose:
          - 4369
          - 5671
          - 5672
          - 25672
          - 15671
        ports:            
            - 15672:15672


    notification_worker:
        build:
          context: .
          dockerfile: ./AppServices/WorkerServices/NotificationWorkerService/Dockerfile        
        container_name: notification_worker
        restart: unless-stopped
        environment: 
          RMQ_USER: "rabbitmq"
          RMQ_PASSWORD: "IlJU7f71Vh7rM1yv"
          RMQ_HOST: "rabbitmq"
          RMQ_PORT: "5672"
          DOTNET_ENVIRONMENT: "Development"
        depends_on:    
          -  rabbitmq  
          

    seq:
     image: datalust/seq
     container_name: seq
     restart: unless-stopped
     expose: 
      - 5341
     ports:
      - 5340:80
     environment: 
      ACCEPT_EULA: Y
     volumes: 
      - seq_data:/data


    prometheus:
      image: prom/prometheus
      container_name: prometheus
      restart: unless-stopped
      ports:
        - 9090:9090
      volumes:
        - ./ThirdPartyImages/prometheus.yml:/etc/prometheus/prometheus.yml:ro


    grafana: 
      image: grafana/grafana      
      environment:
        GF_SECURITY_ADMIN_PASSWORD: "IlJU7f71Vh7rM1yv"
      container_name: grafana
      restart: unless-stopped
      ports:
        - 3000:3000
      volumes: 
        - grafana-storage:/var/lib/grafana grafana/grafana

    angular:
      build:
        context: .
        dockerfile: ./ClientApplications/Angular/Dockerfile        
      container_name: angular
      restart: unless-stopped
      ports:
        - 8888:80
      environment: 
        API_URI: "webapi_nginx:8989/api"
        IS_URI:  "identity_nginx:8989"
      depends_on:        
        - identity_nginx
        - webapi_nginx   


    webapi_nginx:
      build: 
        context: .
        dockerfile: ./AppServices/WebAPIService/nginx/Dockerfile
      container_name: webapi_nginx
      restart: unless-stopped
      ports:
        - 5002:8989
      depends_on: 
        - webapi_service
    

    identity_nginx:
      build: 
        context: .
        dockerfile: ./AppServices/IdentityService/nginx/Dockerfile
      container_name: identity_nginx
      restart: unless-stopped
      ports:
        - 5000:8989
      depends_on: 
        - identity_service
      
  
volumes: 
  pg_data:
  rmq_etc:
  rmq_data:
  rmq_logs:
  seq_data:
  grafana-storage:

